### ISSUE TITLE
Error: timed out on task <ID> when invoking command vlab show centos / winserver

### ISSUE THREAD

**Issue by JohnVo620** [willnx/vlab#2] opened 2018-12-28 15:02 UTC
- vlab status and vlab show onefs work fine

```
C:\Windows\System32>vlab status
Collecting information about your inventory -Collecting information about your inventory
Processing inventory records

Username: vot2
Gateway : 10.25.34.20

Machines:

 Name        | IPs                       | Connectable   | Type      | Version   | Powered   | Console
-------------+---------------------------+---------------+-----------+-----------+-----------+-----------------------------------------------------------------------
 jv-8007-1   | 192.168.1.2               | True          | OneFS     | 8.0.0.7   | On        | https://vlab-dev.igs.corp/api/1/link/2588e48c8c3e286834bc3330f79d9856
 jv-8007-2   | 192.168.1.3               | True          | OneFS     | 8.0.0.7   | On        | https://vlab-dev.igs.corp/api/1/link/44789fa2a87cf17caeffc20aaf66400e
 jv812-4-1   | 192.168.1.4               | True          | OneFS     | 8.1.2.0   | On        | https://vlab-dev.igs.corp/api/1/link/76ed86d6fbdeba23ea41dc77090a23bf
 jvo-centos7 | 192.168.1.150             | True          | CentOS    | 7         | On        | https://vlab-dev.igs.corp/api/1/link/8677ef3f722a0bd20ba1568b01a55769
             | fe80::250:56ff:febc:f02d  |               |           |           |           |
 jvo-win8r2  | fe80::3d74:7c3d:4285:e851 | True          | WinServer | 2008R2    | On        | https://vlab-dev.igs.corp/api/1/link/47839ebb56ce03d71721957723157110
             | 192.168.1.151             |               |           |           |           |


C:\Windows\System32>vlab show onefs
Collecting information about your OneFS nodes
 Name      | IPs   | Type   | Version   | Powered   | Console
-----------+-------+--------+-----------+-----------+-----------------------------------------------------------------------
 jv-8007-1 |       | OneFS  | 8.0.0.7   | On        | https://vlab-dev.igs.corp/api/1/link/a627f8f6d6e6dc31b718bb05a3303016
 jv-8007-2 |       | OneFS  | 8.0.0.7   | On        | https://vlab-dev.igs.corp/api/1/link/43018e2966824315f8a75eacfe64c08b
 jv812-4-1 |       | OneFS  | 8.1.2.0   | On        | https://vlab-dev.igs.corp/api/1/link/b234bf2a457adc452df9a028c85ddb17

C:\Windows\System32>vlab show centos
Collecting information about your CentOS instances
Error: Timed out on task 4471decc-c0e1-4560-87f7-27ed962127fe

C:\Windows\System32>vlab show winserver
Collecting information about your Microsoft Server instances
Error: Timed out on task ef7d6b27-ab75-4c7d-9b58-2f8774373a61
```

**Comment by JohnVo620** [comment] 2018-12-28 15:39
debug file is attached. 

[debug_vlab_show.txt](https://github.com/willnx/vlab/files/2715139/debug_vlab_show.txt)

**Comment by willnx** [comment] 2018-12-28 15:48
Aww crap, I see what's up. The good news is I was planning on fixing this today anyway 😅 

So, when I updated the source for the v2 Beta, I thought _"it would be nice if a deploy would block until the VM boots and gets a DHCP address"_.
https://github.com/willnx/vlab_inf_common/blob/master/vlab_inf_common/vmware/virtual_machine.py#L119

The problem is that making it block by default is a _bad idea_ because if the VM is powered off, or a user (purposefully?) modifies the VM to have no IPs then the back-end service is going to timeout.

**Comment by willnx** [comment] 2018-12-28 17:46
Work on fixing this has begun: https://github.com/willnx/vlab_inf_common/pull/16

This change needs to be propagated to all back-end services that work with VMs, so it'll take some time until it's all done.

**Comment by willnx** [comment] 2018-12-28 18:49
I believe I've propagated the necessary changes to all the back-end services now.
Next step: build docker images and update the server

**Comment by willnx** [comment] 2018-12-28 23:57
New images created and deployed.

I was able to repro the issue with `vlab show centos` on my local box _before_ pushing an update. After the update, it works:
```
PS C:\Users\willhn> vlab show centos
Collecting information about your CentOS instances
 Name    | IPs                      | Type   |   Version | Powered   | Console
---------+--------------------------+--------+-----------+-----------+-----------------------------------------------------------------------
 centos7 | 192.168.1.151            | CentOS |         7 | On        | https://vlab-dev.igs.corp/api/1/link/65b3120f45a34c7c5114aa5c4b3aef04
         | fe80::250:56ff:febc:f2dd |        |           |           |
```

Looks good! Thanks for finding this bug for me @JohnVo620! Closing issue; feel free to reopen if you still have a problem.

**Closed by willnx** 2018-12-28 23:57 UTC
Labels: bug
